SERVER_BINARY=server
 
GO=go

GOFLAGS=

DEST=build/

.PHONY: all clean clean-build build build-server build-server-prepare run watch watchGo watchVite migrate migrate-down migrate-create migrate-force migrate-drop lint lint-js lint-go

include .env

all: build

build:
	$(MAKE) clean-build
	$(MAKE) build-server 

build-server-prepare:
	templ generate
	pnpm vite build
	mv ${DEST}/public/assets/.vite/manifest.json ./internal/middlewares/manifest.json
	cp -r ./public ${DEST}/

build-server: build-server-prepare
	$(GO) build $(GOFLAGS) -o ${DEST}$(SERVER_BINARY) ./cmd/server/.

debug-run: debug
	./build/server

debug:
	rm -rf ./build/public
	mkdir -p ./build
	rm -rf ./build/public
	ln -s ../public/ ./build/public
	$(GO) build -tags debug -o ${DEST}$(SERVER_BINARY) ./cmd/server/.

run: build-server
	cd ${DEST}; ./$(SERVER_BINARY)

dev:
	${MAKE} -j2 watchGo watchVite

watchGo:
	gonova watchexec \
    --templ-dev-mode \
    -i "assets" \
    -i "build" \
    -i "vendor" \
    -i "data" \
    -i "storage" \
    -i "mails" \
    -i "node_modules" \
    -i "resources/scripts" \
    -i "resources/mails/.react-email" \
    -i "resources/mails/out" \
    -i "resources/mails/node_modules" \
    -i "*_templ.go" \
    -e go \
    -e tpl \
    -e tmpl \
    -e html \
	${MAKE} debug-run

watchVite:
	pnpm vite --host --cors true

clean:
	$(GO) clean
	$(MAKE) clean-build

clean-build:
	rm -rf $(DEST)

migrate: 
	gonova migrate up

migrate-down: 
	gonova migrate down --force

migrate-create: 
	gonova migrate create

migrate-force: 
	gonova migrate force --force

migrate-drop: 
	gonova migrate drop --force

lint:
	${MAKE} -j3 lint-go lint-js lint-typechecks

lint-go:
	templ generate
	golangci-lint run ./...

lint-js:
	pnpm run lint

lint-typechecks:
	pnpm run typechecks 

